name: Deploy Backend to Production

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Deploy to Hostinger
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOSTINGER_HOST }}
        username: ${{ secrets.HOSTINGER_USERNAME }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        port: ${{ secrets.HOSTINGER_PORT }}
        script: |
          cd /home/ogsiparis.com/ogBackend
          git pull origin main
          npm install --production
          npx prisma generate
          npx prisma db push
          pm2 restart og-backend || pm2 start server.js --name og-backend --env production
          pm2 save 